"""
Given an array arr[] of N positive elements. The task is to find the Maximum AND 
Value generated by any pair of element from the array.
Note: AND is bitwise '&' operator.

Input:
The first line of the input contains a single integer T, denoting the number of 
test cases. Then T test cases follow. Each test-case has two lines of the input, 
the first line contains an integer denoting the size of an array N and the 
second line of input contains N positive integers

Output:
For each testcase, print Maximum AND Value of a pair in a separate line.

User Task:
The task is to complete the function maxAND() which takes the array elements 
and N (size of array) and input and returns the maximum AND value generated by 
any pair in the array.

Constraints:
1 <=T <= 100
1 <= N <= 100
1 <= arr[i] <= 10^4

Example:
Input:
2
4
4 8 12 16
4
4 8 16 2

Output:
8
0

Explanation:
Testcase 1: Pair (8,12) has the Maximum AND Value  i.e. 8.
Testcase 2: Maximum AND Value is 0.
"""
{
#Initial Template for Python 3
import math
def main():
    
    T=int(input())
    
    while(T>0):
        
        
        n=int(input())
        
        arr=[int(x) for x in input().strip().split()]
        
        print(maxAND(arr,n))
        T-=1
if __name__=="__main__":
    main()
}
''' This is a function problem.You only need to complete the function given below '''
#User function Template for python3
#Complete this function
def maxAND(arr,n):
    #Your code here
    import itertools
    pairs = list(itertools.combinations(arr,2))
    max_and = 0
    if pairs:
        max_and = max([i&j for i,j in pairs])
        return max_and
    else:
        return max_and